name: Deploy to GitHub Page
on:
  push:
    branches:
      - main
jobs:
  run-test-deploy:
    runs-on: node:14-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Install
        run: |
          yarn install
      - name: Unit-Tests
        run: |
          yarn test
      - name: Build-Storybook
        run: |
          yarn build-storybook
          pwd
      - name: Deploy_To_GithubPage
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{ secrets.GIT_PAGE_DEPLOY_MDH_COMPONENT }}
          BRANCH: master # The branch the action should deploy to.
          FOLDER: storybook-static # The folder the action should deploy.
          REPOSITORY_NAME: mydatahack/mydatahack.github.io
          TARGET_FOLDER: mdh-blog-components
          CLEAN: true # Automatically remove deleted files from the deploy branch

  run-release:
    needs: [run-test-deploy]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [14.x]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
          scope: '@mdhnpm'
      - name: Install and build
        run: |
          yarn install
          yarn build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
